#!/usr/bin/lua
local t=require'gluon.site'
local e=require('simple-uci').cursor()
local a=t.usteer({})
local t=e:get_first('usteer','usteer')
e:section('usteer','usteer','usteer',{
enable=a.enabled,
network='mesh',
syslog=1,
debug_level=2,
})
e:commit('usteer')

if(a.enabled == true)
then
os.execute('/etc/init.d/usteer enable')
os.execute('/etc/init.d/usteer start')
else
os.execute('/etc/init.d/usteer stop')
os.execute('/etc/init.d/usteer disable')
end
