#!/usr/bin/lua
local siteDict = require'gluon.site'    
local uciToSet = require('simple-uci').cursor()
local enableStatus = siteDict.usteer({})

uciToSet:section('usteer','usteer','usteer',{
    enabled = enableStatus.enabled,
    network = 'client',
    syslog = 1,
    debug_level = 2,
})
uciToSet:commit('usteer')
